apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-pv-claim
  namespace: todo-app-ns
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi